### ISSUE TITLE
Error on install 

### ISSUE THREAD

**Issue by Ponchia** [appiphony/strike-cli#2]
Hello!

I just made a clean installation of the Strike-CLI, tried to install the lookup component with the following commands:
`strike install strike_lookup -s`
Strike-CLI popup and ask for username and password which I provided.
After that this error came up:
``` upserting strike_utilities.cls
C:\Users\0trezen\AppData\Roaming\npm\node_modules\strike-cli\node_modules\jsforce\lib\connection.js:728
      this._createSingle(type, records, options)
           ^

TypeError: this._createSingle is not a function
    at Tooling.Connection.insert.Connection.create (C:\Users\0trezen\AppData\Roaming\npm\node_modules\strike-cli\node_modules\jsforce\lib\connection.js:728:12)
    at module.exports.SObject.insert.SObject.create (C:\Users\0trezen\AppData\Roaming\npm\node_modules\strike-cli\node_modules\jsforce\lib\sobject.js:62:21)
    at C:\Users\0trezen\AppData\Roaming\npm\node_modules\strike-cli\app.js:336:37
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3) ```


I tried to restard the cmd and also the computer. After that I tried to run the command with the option --sandbox instead of -s and the same error appear.

Any idea? Thanks!

**Comment by Ponchia** [comment]
Node: v8.12.0
OS: W10, Version 10.0.16299 Build 16299
Sorry for the late reply
